name: Docker CI
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
env:
  BETA_CHANNEL: 24.04
  STABLE_CHANNEL: 22.04
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build 22.04
      run: |
        docker build . --pull --build-arg OCIE_VERSION=${{env.STABLE_CHANNEL}} --build-arg PHP_VERSION=8.1 --build-arg SQL_VERSION=5.11.0 --tag bshp/walrus:${{env.STABLE_CHANNEL}} --no-cache
    - name: Push 22.04
      run: |
        docker tag bshp/walrus:${{env.STABLE_CHANNEL}} bshp/walrus:latest
        docker push bshp/walrus:${{env.STABLE_CHANNEL}}
        docker push bshp/walrus:latest
